# Generated by Django 4.2.8 on 2024-01-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nhle_number', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('heritage_designation', models.CharField(max_length=100)),
                ('instance_of', models.TextField()),
                ('historic_county', models.CharField(max_length=100)),
                ('located_in', models.CharField(max_length=100)),
            ],
        ),
    ]
