# Generated by Django 4.2.8 on 2024-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_monument_altitude_monument_architectural_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='architectural_style',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='area',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='country',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='date_established',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='globe',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='historic_county',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='instance_of',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='located_in',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='nhle_number',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='official_website',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='other_designations',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='wikidata_id',
        ),
        migrations.AddField(
            model_name='monument',
            name='admin_entity_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monument',
            name='historic_county_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monument',
            name='image_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monument',
            name='inception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='instance_of_type_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monument',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='heritage_designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='monument',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
