# Generated by Django 4.2.8 on 2024-01-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_monument_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
