# Generated by Django 4.2.8 on 2024-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_monument_country_monument_date_monument_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image_author', models.CharField(blank=True, max_length=255)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
