# Generated by Django 4.2.8 on 2024-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
