# Generated by Django 4.2.8 on 2024-02-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_monument_latitude_alter_monument_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_date',
        ),
    ]
